#!/bin/bash
# eggd_multiqc_to_workbooks 0.0.1
# Generated by dx-app-wizard.
#
# Basic execution pattern: Your app will run on a single machine from
# beginning to end.
#
# Your job's input variables (if any) will be loaded as environment
# variables before this script runs.  Any array inputs will be loaded
# as bash arrays.
#
# Any code outside of main() (or any entry point you may add) is
# ALWAYS executed, followed by running the entry point itself.
#
# See https://documentation.dnanexus.com/developer for tutorials on how
# to modify this file.

main() {

    echo "Value of path_to_multiqc_folder: '$path_to_multiqc_folder'"
    echo "Value of path_to_reports_folder: '$path_to_reports_folder'"

    # Fill in your application code here.
    #
    # To report any recognized errors in the correct format in
    # $HOME/job_error.json and exit this script, you can use the
    # dx-jobutil-report-error utility as follows:
    #
    #   dx-jobutil-report-error "My error message"

    export PATH=$PATH:/home/dnanexus/.local/bin
    #
    # Note however that this entire bash script is executed with -e
    # when running in the cloud, so any line which returns a nonzero
    # exit code will prematurely exit the script; if no error was
    # reported in the job_error.json file, then the failure reason
    # will be AppInternalError with a generic error message.

    echo "environment setup"
    ls

    sudo -H python3 -m pip install --no-index --no-deps /home/dnanexus/packages/*
    mkdir -p /home/dnanexus/out && sudo chmod 757 /home/dnanexus/out

    mkdir multiqc_inputs
    cd multiqc_inputs
    dx download -r "$path_to_multiqc_folder"
    ls
    cd ..


    mkdir reports_inputs
    cd reports_inputs
    dx download -r "$path_to_reports_folder"
    ls
    cd ..

    echo "running python"
    ls 

    python3 annotate_workbooks/annotate_workbooks_with_QC.py
    # The following line(s) use the utility dx-jobutil-add-output to format and
    # add output variables to your job's output as appropriate for the output
    # class.  Run "dx-jobutil-add-output -h" for more information on what it
    # does.
    ls out
    echo "uploading outputs"
    directory_to_make="out/annotated_reports"
    mkdir -p "$directory_to_make"
    mv ./*_QC_added.xlsx "$directory_to_make"


    dx-upload-all-outputs
}
