#!/bin/bash

set -exo pipefail
# eggd_multiqc_to_workbooks 0.0.1
# Generated by dx-app-wizard.
#
# Basic execution pattern: Your app will run on a single machine from
# beginning to end.
#
# Your job's input variables (if any) will be loaded as environment
# variables before this script runs.  Any array inputs will be loaded
# as bash arrays.
#
# Any code outside of main() (or any entry point you may add) is
# ALWAYS executed, followed by running the entry point itself.
#
# See https://documentation.dnanexus.com/developer for tutorials on how
# to modify this file.

main() {

    echo "Value of path_to_multiqc_folder: '$path_to_multiqc_folder'"
    echo "Value of path_to_reports_folder: '$path_to_reports_folder'"
    dx-download-all-inputs --parallel
    # Fill in your application code here.
    #
    # To report any recognized errors in the correct format in
    # $HOME/job_error.json and exit this script, you can use the
    # dx-jobutil-report-error utility as follows:
    #
    #   dx-jobutil-report-error "My error message"

    export PATH=$PATH:/home/dnanexus/.local/bin
    echo "$config_file_path"
    #
    # Note however that this entire bash script is executed with -e
    # when running in the cloud, so any line which returns a nonzero
    # exit code will prematurely exit the script; if no error was
    # reported in the job_error.json file, then the failure reason
    # will be AppInternalError with a generic error message.
    cells_to_edit=$(jq -r '.' "$config_file_path" )
    #echo "$cells_to_edit"

    echo "environment setup"

    # install and download assets
    pip3 install /pytz-*.whl /numpy-*.whl /pandas-*.whl

    sudo -H python3 -m pip install --no-index --no-deps /home/dnanexus/packages/*
    mkdir -p /home/dnanexus/out && sudo chmod 757 /home/dnanexus/out

    multiqc_folder=$(basename "$path_to_multiqc_folder")
    mkdir /home/dnanexus/multiqc_inputs
    cd /home/dnanexus/multiqc_inputs
    dx download -r "$path_to_multiqc_folder"
    cd /home/dnanexus/

    # echo $(basename "$path_to_reports_folder")
    reports_folder=$(basename "$path_to_reports_folder")

    mkdir /home/dnanexus/reports_inputs
    cd /home/dnanexus/reports_inputs
    dx download -r "$path_to_reports_folder"
    cd /home/dnanexus/

    echo "running python"

    python3 annotate_workbooks/annotate_workbooks_with_QC.py --multiqc_folder "$multiqc_folder" --reports_folder "$reports_folder" --config_json "$cells_to_edit" --file_suffix "$file_suffix"
    # The following line(s) use the utility dx-jobutil-add-output to format and
    # add output variables to your job's output as appropriate for the output
    # class.  Run "dx-jobutil-add-output -h" for more information on what it
    # does.

    echo "uploading outputs"
    directory_to_make="out/annotated_reports"
    mkdir -p "$directory_to_make"
    mv ./*"$file_suffix" "$directory_to_make"


    dx-upload-all-outputs
}
